version: "3.8"
services:
  web:
    build: ./cardgen-react
    image: 702351145102.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_web
    command: gunicorn cardgen-react.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 5000
  nginx:
    build: ./nginx
    image: 702351145102.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 5000:80
    depends_on:
      - web
volumes:
  static_volume:


