"""empty message

Revision ID: 297a99546c72
Revises: 9a040b79d381
Create Date: 2023-02-19 00:13:04.820958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297a99546c72'
down_revision = '9a040b79d381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_cards',
    sa.Column('gen_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('gen_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_cards')
    # ### end Alembic commands ###
