"""empty message

Revision ID: bcb5eec1ef96
Revises: 8bb5e058952f
Create Date: 2023-02-17 18:55:48.437001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcb5eec1ef96'
down_revision = '8bb5e058952f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bp', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('hp', sa.String(length=4), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=280), autoincrement=False, nullable=False))
        batch_op.drop_column('hp')
        batch_op.drop_column('bp')
        batch_op.drop_column('description')
        batch_op.drop_column('image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
